qlib_init:
    provider_uri: "../qlib_data/qlib_data"
    region: cn
market: &market csi300
#benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2021-01-01
    end_time: 2021-12-31
    fit_start_time: 2021-01-01
    fit_end_time: 2021-07-31
    instruments: *market
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($vwap, -2) / Ref($vwap, -1) - 1"] 


task:
    model:
        class: GRU
        module_path: qlib.contrib.model.pytorch_gru_ts
        kwargs:
            d_feat: 158
            hidden_size: 64
            num_layers: 2
            dropout: 0.0
            n_epochs: 200
            lr: 0.001
            early_stop: 10
            batch_size: 800
            metric: loss
            loss: batch_ic
            n_jobs: 1
            GPU: 0
    dataset:
        class: TSDatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2021-01-01, 2021-07-31]
                valid: [2021-08-01, 2021-09-30]
                test: [2021-10-01, 2021-12-31]
            step_len: 40
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>


